-- TABLAS 

CREATE TABLE IF NOT EXISTS publishers(
    id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL
);

CREATE TABLE IF NOT EXISTS authors(
    id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL
);

CREATE TABLE IF NOT EXISTS members(
    id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    first_name VARCHAR(100) NOT NULL,
    last_name VARCHAR(100) NOT NULL,
    street_address VARCHAR(100) NOT NULL,
    city VARCHAR(100) NOT NULL,
    state_m VARCHAR(100) NOT NULL,
    zip_code VARCHAR(10) NOT NULL
);

CREATE TABLE IF NOT EXISTS books(
    id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    title VARCHAR(100) NOT NULL,
    publisher_id INT REFERENCES publishers(id),
    author_id INT REFERENCES authors(id)
);

CREATE TABLE IF NOT EXISTS book_transactions(
    id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    tran_date  DATE NOT NULL,
    type_ VARCHAR(10) NOT NULL,
    book_id INT REFERENCES books(id),
    member_id INT REFERENCES members(id)
);